language: python
python:
- '2.7'
sudo: required
services:
- docker
before_install:
- docker --version
- docker-compose --version
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- sleep 30
- docker exec docker_tumblrharvester_1 python -m unittest discover
install: pip install -r requirements/common.txt -r requirements/master.txt
script: python -m unittest discover
notifications:
  email:
  - ychtan@email.gwu.edu
  slack:
    on_success: never
