language: python
python:
- '2.7'
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
- sudo pip install -U docker-compose
- sudo pip install --upgrade ndg-httpsclient
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- sleep 30
- docker exec docker_sfmtumblrharvester_1 python -m unittest discover
install: pip install -r requirements/common.txt -r requirements/master.txt
script: python -m unittest discover
notifications:
  email:
  - ychtan@email.gwu.edu
  slack:
    on_success: never
