version: "2"
services:
  rabbit:
      image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
      environment:
          - TZ=America/New_York
          - RABBITMQ_DEFAULT_USER=sfm_user
          - RABBITMQ_DEFAULT_PASS=password
  tumblrharvester:
      image: gwul/sfm-tumblr-harvester:master
      links:
          - rabbit:mq
      volumes:
          - "..:/opt/sfm-tumblr-harvester"
      environment:
          - TZ=America/New_York
          - TUMBLR_API_KEY
          - SFM_REQS=master
          - RABBITMQ_USER=sfm_user
          - RABBITMQ_PASSWORD=password
          - DEBUG=true
          - HARVEST_TRIES=3